#!/bin/sh
# start wpa_supplicant with dbus support
PIDFILE=/var/run/wpa_supplicant.pid

case "$1" in
    start)
        /usr/sbin/wpa_supplicant -u -B -P "$PIDFILE"
        ;;
    stop)
        start-stop-daemon -K -q -p "$PIDFILE" 2>/dev/null || true
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
